; Auto-generated. Do not edit!


(cl:in-package behavior_tree_core-msg)


;//! \htmlinclude BTGoal.msg.html

(cl:defclass <BTGoal> (roslisp-msg-protocol:ros-message)
  ((parameter
    :reader parameter
    :initarg :parameter
    :type cl:integer
    :initform 0))
)

(cl:defclass BTGoal (<BTGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <BTGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'BTGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name behavior_tree_core-msg:<BTGoal> is deprecated: use behavior_tree_core-msg:BTGoal instead.")))

(cl:ensure-generic-function 'parameter-val :lambda-list '(m))
(cl:defmethod parameter-val ((m <BTGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader behavior_tree_core-msg:parameter-val is deprecated.  Use behavior_tree_core-msg:parameter instead.")
  (parameter m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <BTGoal>) ostream)
  "Serializes a message object of type '<BTGoal>"
  (cl:let* ((signed (cl:slot-value msg 'parameter)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <BTGoal>) istream)
  "Deserializes a message object of type '<BTGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'parameter) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<BTGoal>)))
  "Returns string type for a message object of type '<BTGoal>"
  "behavior_tree_core/BTGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'BTGoal)))
  "Returns string type for a message object of type 'BTGoal"
  "behavior_tree_core/BTGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<BTGoal>)))
  "Returns md5sum for a message object of type '<BTGoal>"
  "3b5e34835331aac7a9065c5abd204e3b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'BTGoal)))
  "Returns md5sum for a message object of type 'BTGoal"
  "3b5e34835331aac7a9065c5abd204e3b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<BTGoal>)))
  "Returns full string definition for message of type '<BTGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 parameter #no goal needed for BT tick. But It could be useful to have a parameter for action (e.g.goto x,y)~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'BTGoal)))
  "Returns full string definition for message of type 'BTGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 parameter #no goal needed for BT tick. But It could be useful to have a parameter for action (e.g.goto x,y)~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <BTGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <BTGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'BTGoal
    (cl:cons ':parameter (parameter msg))
))
