; Auto-generated. Do not edit!


(cl:in-package behavior_tree_core-msg)


;//! \htmlinclude BTResult.msg.html

(cl:defclass <BTResult> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type cl:integer
    :initform 0))
)

(cl:defclass BTResult (<BTResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <BTResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'BTResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name behavior_tree_core-msg:<BTResult> is deprecated: use behavior_tree_core-msg:BTResult instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <BTResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader behavior_tree_core-msg:status-val is deprecated.  Use behavior_tree_core-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <BTResult>) ostream)
  "Serializes a message object of type '<BTResult>"
  (cl:let* ((signed (cl:slot-value msg 'status)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <BTResult>) istream)
  "Deserializes a message object of type '<BTResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'status) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<BTResult>)))
  "Returns string type for a message object of type '<BTResult>"
  "behavior_tree_core/BTResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'BTResult)))
  "Returns string type for a message object of type 'BTResult"
  "behavior_tree_core/BTResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<BTResult>)))
  "Returns md5sum for a message object of type '<BTResult>"
  "86791dcf1de997ec7de5a0de7e4dcfcc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'BTResult)))
  "Returns md5sum for a message object of type 'BTResult"
  "86791dcf1de997ec7de5a0de7e4dcfcc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<BTResult>)))
  "Returns full string definition for message of type '<BTResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition RUNNING = 0, SUCCESS = 1, FAILURE = 2~%int32 status~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'BTResult)))
  "Returns full string definition for message of type 'BTResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition RUNNING = 0, SUCCESS = 1, FAILURE = 2~%int32 status~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <BTResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <BTResult>))
  "Converts a ROS message object to a list"
  (cl:list 'BTResult
    (cl:cons ':status (status msg))
))
